version: '2'
services:
  vk-callbak-api-server:
    image: danyanya/vk-callbak-api-server
    build: .
    command: /usr/bin/vk-callback-api 
    ports:
      - 9911:9911
    environment:  
      - CONF_CODE=123456
      - MINDBOX_URL=http://api.vk.com/1
      - MINDBOX_KEY=123
      - MINDBOX_BRAND=meow
      - MINDBOX_POINT_OF_CONTACT=kitten-vk

